### ISSUE TITLE
Corrections to README.md

### ISSUE THREAD

**Issue by pdigre** [cdietrich/xtext-languageserver-example#14]
I was able to run it with Java 11 and Eclipse Sep-2018, though instructions are a little bit different.

1. change the npm install command, needs to "-g"
npm install -g vsce
2. To run scenario 2, I had to first run the build "vsce package" and therafter the commands were ..
code --install-extension vscode-extension-self-contained/xtext-vscode-example-0.0.14.vsix
code demo

**Comment by cdietrich** [comment]
If you run npm install in both extensions you should be able to start them in debug mode(extension host) by opening the extension package in code and hitting f5

**Comment by cdietrich** [comment]
And yes you either need to install vice globally or first move into the package before calling install

**Comment by cdietrich** [comment]
updated readme regarding vsce
