### ISSUE TITLE
syntax highlighting does not work in vscode

### ISSUE THREAD

**Issue by tsjfd** [cdietrich/xtext-languageserver-example#17]
It seams to be that `mydsl.configuration.json` is ignored by vscode. Comments e.g. are not highlighted.

**Comment by cdietrich** [comment]
correct. in the current config the text mate grammar at mydsl.tmLanguage is used which misses comments

**Comment by cdietrich** [comment]
Version with extended text mate grammar (migrated from plist to json) is live now
