### ISSUE TITLE
Formatting uses tabs when the model is updated from the CommandService

### ISSUE THREAD

**Issue by pmeijer** [cdietrich/xtext-languageserver-example#53]
For our domain we have a command defined in vscode that assigns a uuid to each model element and as part of that it saves the model back to the files. 
The problem were having is that thru this invocation point the formatting is inserting tabs rather than spaces. However when explicitly using the dsl-formatter spaces are inserted.

My vscode is configured to use spaces:
```
    "editor.detectIndentation": false,
    "editor.tabSize": 4,
    "editor.insertSpaces": true,
```

I'm not sure how to come around this issue. Any help appreciated.

**Comment by cdietrich** [comment]
Have a look how the formatter in Xtext configures tabs vs spaces and configure yours to preference

**Comment by pmeijer** [comment]
Any chance you can point me to the equivalent file here in this repo and show me how that configuration parameter is set?

**Comment by pmeijer** [comment]
Turns out this was only an issue in debug mode (running the extension using the extension development host).
