### ISSUE TITLE
Code Generation

### ISSUE THREAD

**Issue by mzaks** [cdietrich/xtext-languageserver-example#7]
Would it be possible to add a command invoking code generation?

Thanks in advance.

**Comment by cdietrich** [comment]
hi,

code generation is enabled by default, so you actually dont need a command.

**Comment by mzaks** [comment]
Hm, but I don#t see the `src-gen` folder and corresponding `java` files anywhere.

**Comment by cdietrich** [comment]
which version do you use? a locally built? or the one from the store?

**Comment by mzaks** [comment]
locally build, ach is it commented out :)

**Comment by cdietrich** [comment]
a i havent rebased this on stuff from itemis yet

**Comment by cdietrich** [comment]
please pull again :)

**Comment by mzaks** [comment]
Now it works, thank you!

I guess rename refactoring and quick fixes are out of the ls-api scope?

**Comment by cdietrich** [comment]
they are not yet done. but at least rename support is part of the protocol https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#rename

**Comment by mzaks** [comment]
Cool! Thanks again.
