### ISSUE TITLE
Visual Studio Code extension does not work on Windows

### ISSUE THREAD

**Issue by Xpitfire** [cdietrich/xtext-languageserver-example#9]
It seems that there are some troubles on Windows with the Xtext Server startup. Can you take a look at this and fix this? Thank you.
Test Environment:
- Windows 10 Build 14393
- VS Code v1.8.0

I also tested the same visx file on Ubuntu 16.04 and everything seems to work fine.

![image](https://cloud.githubusercontent.com/assets/7037963/21290627/62c5c8f4-c4c2-11e6-8541-40839a1796eb.png)

**Comment by cdietrich** [comment]
did you test this when starting from gradle or with the version from the store?

**Comment by cdietrich** [comment]
can you please retry

**Comment by cdietrich** [comment]
should be fixed now

**Comment by Xpitfire** [comment]
Sorry, for the delayed response and thank you for the fix. I tested the new version and everything works fine.
